# Generated by Django 5.1.6 on 2025-04-03 17:17

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('profile_app', '0011_alter_message_media_alter_message_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='price',
            new_name='bidding_price',
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_balance', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='profile_app.userprofile')),
            ],
        ),
    ]
