# Generated by Django 5.1.6 on 2025-04-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_price_artifact_bidding_price_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
