# Generated by Django 5.1.6 on 2025-03-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_message_encrypted_content_userprofile_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encrypted_content',
        ),
        migrations.DeleteModel(
            name='MediaMessage',
        ),
    ]
