# Generated by Django 5.1.6 on 2025-03-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_remove_message_encrypted_content_delete_mediamessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
