# Generated by Django 5.1.6 on 2025-03-19 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_alter_message_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
    ]
