# Generated by Django 5.1.6 on 2025-03-31 11:55

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_remove_userprofile_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
