# Generated by Django 5.1.6 on 2025-03-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_group_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='messages/media/'),
        ),
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='messages/media/'),
        ),
    ]
