# Generated by Django 5.1.6 on 2025-04-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0013_alter_message_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
