# Generated by Django 5.1.6 on 2025-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0014_alter_message_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
