# Generated by Django 5.1.6 on 2025-04-06 23:06

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0016_alter_message_media_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='messages/media/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
